### PR TITLE
fix not defined symbol null pointer error

### PR DESCRIPTION
**Pull request by YuanyuanZh**

### CODE REVIEW

**Comment by parrt** [comment]
btw, did all tests pass? ;)  i.e., did you check whether this breaks something?

**Comment by YuanyuanZh** [comment]
it will not effect others tests, because I just add a if to check whether the exprtype is null, checkType is the last tree walking before code gen , at this time all expression should have type information , except the symbol which is not defined.

**Comment by parrt** [comment]
"should" is not what automated testing is about. ;)  I'll run the tests for you but tests are there to check reality not what we believe is true :)

**Comment by YuanyuanZh** [comment]
shuai already have the Symbol_not_defined error, before x = x1  " var x = 1 , x = x1" , since you told her we should get all compiler errors not just one once we encountered, so it will continue walk the tree again, in checkType she need expression type, but it is null if symbol is not defined, so we have the null pointer error

**Pull request merged**
