### PR TITLE
Shuai

### PR DESCRIPTION
**Pull request by syuanivy**
Define symbol, compute type and type checking without promotion.

### CODE REVIEW

**Comment by parrt** [comment]
First comment is that you should use a branch name like "add symtab management" not "shuai" ;)

**Comment by parrt** [comment]
Also a good idea to collapse most of the commits into logical chunks once you're happy with the branch. In this case, I might suggest squashing into one commit.  The easy way is to checkout your feature branch and then reset *SOFT* to the commit before your first commit on the feature branch. the commit all those staged changes as one commit.  E.g., 

```
...
commit fb9e1f03a52b8a94c98b617a5917d78c74dc4ef5
Author: syuanivy <syuanivy@gmail.com>
Date:   Wed Sep 9 15:56:15 2015 -0700

    Define Symbol, compute type, type checking without promotion.

commit df2ad21fb54c64935a34ad4ee0d6f2c1fae3fb24
Author: Terence Parr <parrt@cs.usfca.edu>
Date:   Wed Sep 9 14:27:41 2015 -0700

    improve ref counting GC and update tests
...
```

I fetched and checked out your branch locally and then did the reset/commit w/o pushing back to you of course. try it out :)

```
terence:~/github/wich-c/runtime/test $ git reset df2ad21fb54c64935a34ad4ee0d6f2c1fae3fb24
Unstaged changes after reset:
M	trans/src/wich/Trans.java
M	trans/src/wich/parser/SymbolTableConstructor.java
M	trans/src/wich/parser/TypeAnnotator.java
M	trans/src/wich/parser/TypeChecker.java
M	trans/src/wich/parser/Wich.g4
M	trans/src/wich/semantics/type/WPrimitiveType.java
terence:~/github/wich-c/runtime/test $ git commit -a -m 'define symbols, compute types, do type checking w/o promotion'
[add-symtab 1279c5e] define symbols, compute types, do type checking w/o promotion
 6 files changed, 286 insertions(+), 25 deletions(-)
terence:~/github/wich-c/runtime/test $ git log 
commit 1279c5ed8fa5802a5fad10903bf263acb5010676
Author: Terence Parr <parrt@antlr.org>
Date:   Wed Sep 9 17:23:01 2015 -0700

    define symbols, compute types, do type checking w/o promotion

commit df2ad21fb54c64935a34ad4ee0d6f2c1fae3fb24
Author: Terence Parr <parrt@cs.usfca.edu>
Date:   Wed Sep 9 14:27:41 2015 -0700

    improve ref counting GC and update tests
...
```

Like magic, you have a single commit :)  Try that to see if it works for you.

**Comment by syuanivy** [comment]
Yes! That works, all combined!

**Comment by parrt** [comment]
did you push to origin? I think i see your old commits still.

**Comment by parrt** [comment]
Closing in favor of https://github.com/langwich/wich-c/pull/6

**Pull request closed without merging**
